/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Production</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Production#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Production#getRigth <em>Rigth</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProduction()
 * @model
 * @generated
 */
public interface Production extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(NonTerminal)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProduction_Left()
   * @model containment="true"
   * @generated
   */
  NonTerminal getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Production#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(NonTerminal value);

  /**
   * Returns the value of the '<em><b>Rigth</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Rigth}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rigth</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProduction_Rigth()
   * @model containment="true"
   * @generated
   */
  EList<Rigth> getRigth();

} // Production
