/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.GNFC.ui.internal.GNFCActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GNFCActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
