/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRigthAccess().getAlternatives(), "rule__Rigth__Alternatives");
			builder.put(grammarAccess.getSimpleAccess().getAlphaAlternatives_1_0(), "rule__Simple__AlphaAlternatives_1_0");
			builder.put(grammarAccess.getNonTerminalAccess().getVarAlternatives_1_0(), "rule__NonTerminal__VarAlternatives_1_0");
			builder.put(grammarAccess.getGNFCAccess().getGroup(), "rule__GNFC__Group__0");
			builder.put(grammarAccess.getInitialAccess().getGroup(), "rule__Initial__Group__0");
			builder.put(grammarAccess.getInitialAccess().getGroup_3(), "rule__Initial__Group_3__0");
			builder.put(grammarAccess.getProductionAccess().getGroup(), "rule__Production__Group__0");
			builder.put(grammarAccess.getProductionAccess().getGroup_3(), "rule__Production__Group_3__0");
			builder.put(grammarAccess.getSimpleAccess().getGroup(), "rule__Simple__Group__0");
			builder.put(grammarAccess.getNonTerminalAccess().getGroup(), "rule__NonTerminal__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup(), "rule__Binary__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup_1(), "rule__Binary__Group_1__0");
			builder.put(grammarAccess.getGNFCAccess().getWAssignment_0(), "rule__GNFC__WAssignment_0");
			builder.put(grammarAccess.getGNFCAccess().getWAssignment_1(), "rule__GNFC__WAssignment_1");
			builder.put(grammarAccess.getGNFCAccess().getInitAssignment_2(), "rule__GNFC__InitAssignment_2");
			builder.put(grammarAccess.getGNFCAccess().getProductionsAssignment_3(), "rule__GNFC__ProductionsAssignment_3");
			builder.put(grammarAccess.getInitialAccess().getLeftAssignment_0(), "rule__Initial__LeftAssignment_0");
			builder.put(grammarAccess.getInitialAccess().getRigthAssignment_2(), "rule__Initial__RigthAssignment_2");
			builder.put(grammarAccess.getInitialAccess().getRigthAssignment_3_1(), "rule__Initial__RigthAssignment_3_1");
			builder.put(grammarAccess.getProductionAccess().getLeftAssignment_0(), "rule__Production__LeftAssignment_0");
			builder.put(grammarAccess.getProductionAccess().getRigthAssignment_2(), "rule__Production__RigthAssignment_2");
			builder.put(grammarAccess.getProductionAccess().getRigthAssignment_3_1(), "rule__Production__RigthAssignment_3_1");
			builder.put(grammarAccess.getRigthAccess().getSimpleAssignment_0(), "rule__Rigth__SimpleAssignment_0");
			builder.put(grammarAccess.getRigthAccess().getBinaryAssignment_1(), "rule__Rigth__BinaryAssignment_1");
			builder.put(grammarAccess.getSimpleAccess().getAlphaAssignment_1(), "rule__Simple__AlphaAssignment_1");
			builder.put(grammarAccess.getNonTerminalAccess().getVarAssignment_1(), "rule__NonTerminal__VarAssignment_1");
			builder.put(grammarAccess.getBinaryAccess().getFirstAssignment_1_0(), "rule__Binary__FirstAssignment_1_0");
			builder.put(grammarAccess.getBinaryAccess().getSecondAssignment_1_1(), "rule__Binary__SecondAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
